- name: Push to Hugging Face
  uses: nateraw/huggingface-sync-action@v0.0.5
  with:
    github_repo_id: build-small-hackathon/1000-Rooms
    huggingface_repo_id: build-small-hackathon/1000-Rooms
    hf_token: ${{ secrets.HF_TOKEN }}
